volumes:
  music: |
    - name: libretime-storage
      nfs:
        server: 192.168.1.26
        path: /Data02/radio

publicUrl: https://console.thruhere.net
publicHost: console.thruhere.net
streamUrl: https://radio.thruhere.net/main
streamHost: radio.thruhere.net

nginx:
  repository:
    image: nginx
    tag: latest
  service:
    port: 8080
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: lets-encrypt
      kubernetes.io/ingress.class: nginx
api:
  repository:
    image: ghcr.io/libretime/libretime-api
    tag: latest
  service:
    port: 9001
  config:
    general:
      api_key: libretime
      secret_key: libretime
      allowed_cors_origins:
        - "https://publicUrl"
      timezone: Europe/London
      cache_ahead_hours: 1
      auth: local
email:
  fromaddress: admin@radio.thruhere.net
  host: localhost
  port: 25
postgres:
  external: false
  repository:
    image: postgres
    tag: "15"
  secret:
    existingSecret: "" 
    username: libretime
    password: admin
    passwordBase64:  YWRtaW4=    # For db statefulset, base64 encoded value. YWRtaW4= "admin"
  persistence:
    existingClaim: ""
  service:
    port: 5432
rabbitmq:
  repository:
    image: rabbitmq
    tag: 3.12-alpine
  secret:
    existingSecret: ""
    username: libretime
    password: libretimePassword
  service:
    port: 5672
playout:
  repository:
    image: ghcr.io/libretime/libretime-playout
    tag: latest
liquidsoap:
  repository:
    image: ghcr.io/libretime/libretime-playout
    tag: latest
analyzer:
  repository:
    image: ghcr.io/libretime/libretime-analyzer
    tag: latest
worker:
  repository:
    image: ghcr.io/libretime/libretime-worker
    tag: latest
legacy:
  repository:
    image: ghcr.io/libretime/libretime-legacy
    tag: latest
  service:
    port: 9000
icecast:
  repository:
    image: ghcr.io/libretime/icecast
    tag: latest
  stream:
    name: thruhere.fm
    mountpoint: main
    description: thruhere.fm
    website: https://www.radio.thruhere.net
    genre: "thruhere.fm"
    passwords:
      source: libretime
      admin: libretime
      relay: libretime
  service:
    port: 8000

