publicUrl: https://console.thruhere.net
publicHost: console.thruhere.net
streamUrl: https://radio.thruhere.net/main
streamHost: radio.thruhere.net
showHost: https://show.thruhere.net

volumes: 
  radiovolume: |
    - name: radiovolume
      nfs:
        server: 192.168.1.26
        path: /Data02/thruhere
  library: |
    - name: library
      nfs:
        server: 192.168.1.26
        path: /Data01/cdcollection

libraryscan:
  enabled: true
  schedule: "*/10 * * * *"

nginx:
  repository:
    image: nginx
    tag: latest
#  service:
#    port: 8080
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: lets-encrypt
      kubernetes.io/ingress.class: nginx

api:
  repository:
    image: ghcr.io/libretime/libretime-api
    tag: latest
#  service:
#    port: 9001
  config:
    general:
      api_key: libretime
      secret_key: libretime
      allowed_cors_origins:
        - "https://radio.thruhere.net"
      timezone: Europe/London
      cache_ahead_hours: 1
      auth: local

email:
  fromaddress: motttt@muso.club
  host: localhost
  port: 25

postgres:
  storage:
    class: ceph-rbd
    size: 5Gi
  backup:
    enabled: true
    schedule:  "0 1 * * *"
  restore:
    enabled: false
    date: 2024-06-14-00-00
  repository:
    image: postgres
    tag: "16.2"
  secret:
    username: libretime
    password: admin
#  service:
#    port: 5432

rabbitmq:
  repository:
    image: rabbitmq
    tag: 3.12-alpine
  secret:
    username: libretime
    password: libretimePassword
#  service:
#    port: 5672

icecast:
  location: UK
  email: motttt@muso.radio
  loglevel: information
  limits:
    clients: 100
    sources: 6
    burstsize: 65535
  repository:
    image: ghcr.io/libretime/icecast
    tag: latest
  stream:
    name: thruhere.net
    mountpoint: main
    description: thruhere.net
    website: https://www.radio.thruhere.net
    genre: "thruhere.net"
    authentication:
      sourcepassword: libretime
      relaypassword: libretime
      adminuser: admin
      adminpassword: libretime
    passwords:
      source: libretime
      admin: libretime
      relay: libretime
  # service: 
  #  port: 8000
  mount1:
    name: stream1
    username: stream1
    password: stream1Password
    intro: stream1Intro.mpg    
    fallbackmount: /main
    streamname: "ThruHereStream01"
    streamdescription: "Stream 1 on ThruHere Radio, a PodZone Project" 
    streamurl: "https://www.radio.thruhere.net"
  mount2:
    name: stream2
    username: stream2
    password: stream2Password
    intro: stream2Intro.mpg
    fallbackmount: /main
    streamname: "ThruHereStream02"
    streamdescription: "Stream 2 on ThruHere Radio, a PodZone Project" 
    streamurl: "https://www.radio.thruhere.net"

playout:
  repository:
    image: ghcr.io/libretime/libretime-playout
    tag: latest
liquidsoap:
  repository:
    image: ghcr.io/libretime/libretime-playout
    tag: latest
analyzer:
  repository:
    image: ghcr.io/libretime/libretime-analyzer
    tag: latest
worker:
  repository:
    image: ghcr.io/libretime/libretime-worker
    tag: latest
legacy:
  repository:
    image: ghcr.io/libretime/libretime-legacy
    tag: latest
#  service:
#    port: 9000
