apiVersion: v1
kind: Service
metadata:
  labels:
    libretime.service: web
  name: web
spec:
  ports:
    - name: "{{ .Values.nginx.service.port }}"
      port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.port }}
  selector:
    libretime.service: web
