apiVersion: v1 
kind: Secret 
metadata: 
  name: pgpass-secret 
type: Opaque 
stringData:
  .pgpass: "postgres:5432:libretime:libretime:{{ .Values.postgres.secret }}"
#data: 
#  .pgpass: cG9zdGdyZXM6NTQzMjpsaWJyZXRpbWU6bGlicmV0aW1lOnAwNXRicjM1Cg==
#echo "postgres:5432:libretime:libretime:p05tbr35" | base64