apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: libretime
  POSTGRES_USER: {{ .Values.postgres.secret.username }}
  PGDATA: /var/lib/postgresql/data/pgdata
