apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    libretime.service: icecast
  name: icecast
spec:
  replicas: 1
  selector:
    matchLabels:
      libretime.service: icecast
  template:
    metadata:
      labels:
        libretime.service: icecast
    spec:
      containers:
        - name: icecast
          image: {{ .Values.icecast.repository.image }}:{{ .Values.icecast.repository.tag }}
          volumeMounts:
            - mountPath: /etc/icecast2/icecast.xml
              subPath: icecast.xml
              name: icecast-conf
              readOnly: true
            - mountPath: /web
              name: icecast-web
            - mountPath: /log
              name: icecast-log
          ports:
            - containerPort: {{ .Values.icecast.service.port }}
              protocol: TCP
      restartPolicy: Always
      automountServiceAccountToken: false
      volumes:
        - name: icecast-conf
          secret:
            secretName: icecast-conf
            items:
              - key: icecast.xml
                path: icecast.xml
{{ .Values.volumes.web | indent 8 }}
{{ .Values.volumes.log | indent 8 }}