apiVersion: v1
kind: Service
metadata:
  labels:
    libretime.service: icecast
  name: icecast
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    libretime.service: icecast
