<icecast>
    <location>Earth</location>
    <admin>icemaster@localhost</admin>
    <hostname>localhost</hostname>
    <limits>
        <clients>100</clients>
        <sources>2</sources>
        <queue-size>524288</queue-size>
        <client-timeout>30</client-timeout>
        <header-timeout>15</header-timeout>
        <source-timeout>10</source-timeout>
        <burst-size>65535</burst-size>
    </limits>
    <authentication>
        <source-password>hackme</source-password>
        <relay-password>hackme</relay-password>
        <admin-user>admin</admin-user>
        <admin-password>hackme</admin-password>
    </authentication>
    <listen-socket>
        <port>8000</port>
    </listen-socket>
    <http-headers>
        <header type="cors" name="Access-Control-Allow-Origin" />
        <header type="cors" name="Access-Control-Allow-Headers" />
        <header type="cors" name="Access-Control-Expose-Headers" />
    </http-headers>
    <paths>
        <basedir>@pkgdatadir@</basedir>
        <logdir>@localstatedir@/log/@PACKAGE@</logdir>
        <webroot>@pkgdatadir@/web</webroot>
        <adminroot>@pkgdatadir@/admin</adminroot>
        <reportxmldb>@pkgdatadir@/report-db.xml</reportxmldb>
        <alias source="/" destination="/status.xsl"/>
    </paths>
    <logging>
        <accesslog>access.log</accesslog>
        <errorlog>error.log</errorlog>
        <loglevel>information</loglevel>
        <logsize>10000</logsize>
    </logging>
    <security>
        <chroot>false</chroot>
        <tls-context>
        </tls-context>
    </security>
</icecast>