apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    libretime.service: icecast
  name: icecast
spec:
  replicas: 1
  selector:
    matchLabels:
      libretime.service: icecast
  template:
    metadata:
      labels:
        libretime.service: icecast
    spec:
      initContainers:
      - name: copy-files
        image: {{ .Values.icecast.repository.image }}:{{ .Values.icecast.repository.tag }}
        command: ['sh', '-c', 'cp -vR /web/* /mnt']
        volumeMounts:
          - name: radiovolume
            subPath: icecastweb
            mountPath: /mnt
      containers:
        - name: icecast
          image: {{ .Values.icecast.repository.image }}:{{ .Values.icecast.repository.tag }}
          volumeMounts:
            - mountPath: /etc/icecast.xml
              subPath: icecast.xml
              name: icecast-conf
              readOnly: true
            - mountPath: /web
              name: radiovolume
              subPath: icecastweb
          ports:
            - containerPort: {{ .Values.icecast.service.port }}
              protocol: TCP
      restartPolicy: Always
      automountServiceAccountToken: false
      volumes:
        - name: icecast-conf
          configMap:
            name: icecast-conf
            items:
              - key: icecast.xml
                path: icecast.xml
{{ .Values.volumes.radiovolume | indent 8 }}

