# Deprecate
apiVersion: v1 
kind: Secret
metadata:
  creationTimestamp: null
  name: icecast-passwords
stringData:
  ICECAST_ADMIN_PASSWORD: {{ .Values.icecast.stream.passwords.admin | quote }}
  ICECAST_RELAY_PASSWORD: {{ .Values.icecast.stream.passwords.relay | quote }}
  ICECAST_SOURCE_PASSWORD: {{ .Values.icecast.stream.passwords.source | quote }}
