apiVersion: v1
kind: Service
metadata:
  labels:
    libretime.service: api
  name: api
spec:
  ports:
    - name: {{ .Values.api.service.port | quote }}
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
  selector:
    libretime.service: api
