apiVersion: v1
kind: Service
metadata:
  labels:
    libretime.service: api
  name: api
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    libretime.service: api
