apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    libretime.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      libretime.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        libretime.service: api
    spec:
      initContainers:
      {{- if .Values.postgres.restore.enabled }}
      - name: restore-db
        image: "{{ .Values.postgres.repository.image }}:{{ .Values.postgres.repository.tag }}"
        command:
          - '/bin/sh'
          - '-c'
          - 'echo "Starting restore of dbbackup-{{ .Values.postgres.restore.date }}." 
              && pwd && cd ~ && ls -al && && echo $PGPASSFILE &&
              pg_restore -d libretime -h postgres -p 5432 /mnt/dbbackup-{{ .Values.postgres.restore.date }}'
        env:
          - name: PGPASSFILE
            value: ~/.pgpass
        volumeMounts:
          - name: radiovolume
            mountPath: /mnt
            subPath: backup
          - name: pgpass-volume
            mountPath: ~/.pgpass
            subPath: ~.pgpass
      {{- else }}
      - name: run-migration
        image: "{{ .Values.api.repository.image }}:{{ .Values.api.repository.tag }}"
        command: ['sh', '-c', 'echo "Creating a new database." && pwd && ls -al && libretime-api migrate']
        volumeMounts:
          - mountPath: /etc/libretime/config.yml
            subPath: config.yml
            name: libretime-conf
            readOnly: true
          - mountPath: /srv/libretime
            name: radiovolume
            subPath: libretime
      {{- end }}
      containers:
        - image: "{{ .Values.api.repository.image }}:{{ .Values.api.repository.tag }}"
          name: api
          volumeMounts:
            - mountPath: /etc/libretime/config.yml
              subPath: config.yml
              name: libretime-conf
              readOnly: true
            - mountPath: /srv/libretime
              name: radiovolume
              subPath: libretime
      restartPolicy: Always
      automountServiceAccountToken: false
      volumes:
        - name: libretime-conf
          secret:
            secretName: libretime-conf
            items:
              - key: config.yml
                path: config.yml
        - name: pgpass-volume
          secret:
            secretName: pgpass-secret
            defaultMode: 384
{{ .Values.volumes.radiovolume | indent 8 }}







