apiVersion: batch/v1
kind: CronJob
metadata:
  name: library-scan
spec:
  schedule:  {{ .Values.libraryscan.schedule | squote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: library-scan
              image: "{{ .Values.api.repository.image }}:{{ .Values.api.repository.tag }}"
              command: ['sh', '-c', 'flock -n /srv/libretime/library-scan.lock libretime-api bulk_import --path /library 2>> /mnt/libretime/libretime_scan.log']
              resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
              volumeMounts:
                - mountPath: /etc/libretime/config.yml
                  subPath: config.yml
                  name: libretime-conf
                  readOnly: true
                - mountPath: /srv/libretime
                  name: radiovolume
                  subPath: libretime
                - mountPath: /library
                  name: library
          volumes:
            - name: libretime-conf
              secret:
                secretName: libretime-conf
                items:
                  - key: config.yml
                    path: config.yml
{{ .Values.volumes.radiovolume | indent 12 }}
{{ .Values.volumes.library | indent 12 }}