apiVersion: v1
kind: Service
metadata:
  labels:
    libretime.service: postgres
  name: postgres
spec:
  ports:
    - name: "{{ .Values.postgres.service.port }}"
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
  selector:
    libretime.service: postgres