apiVersion: v1
kind: Service
metadata:
  labels:
    libretime.service: rabbitmq
  name: rabbitmq
spec:
  ports:
    - name: "{{ .Values.rabbitmq.service.port }}"
      port: {{ .Values.rabbitmq.service.port }}
      targetPort: {{ .Values.rabbitmq.service.port }}
  selector:
    libretime.service: rabbitmq
