apiVersion: cert-manager.io/v1 
kind: Certificate
metadata:
  name: {{ .Values.publicHost }}-cert
spec:
  dnsNames:
  - {{ .Values.publicHost }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: lets-encrypt
  secretName: {{ .Values.publicHost }}-cert
